services:

  # START OF DATABASE CONTAINERS

  mariadb-schedule:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: changeme
    volumes:
      - schedule_data:/var/lib/mysql/

  mongodb-artist:
    image: mongo
    restart: always
    ports:
      - 3307:27017
    volumes:
      - artist_data:/data/db
  
  mysql-food:
    image: mysql
    restart: always
    ports: 
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      - food_data:/var/lib/mysql

  mariadb_stage:
    image: mariadb
    restart: always
    ports:
      - 3309:3306
    environment:
      MARIADB_ROOT_PASSWORD: changeme
    volumes:
      - stage_data:/var/lib/mysql

  # START OF SERVICE CONTAINERS
  # ....
  

  # START OF DATA VOLUMES
volumes:
  schedule_data:
  artist_data:
  food_data:
  stage_data:
