services:
  # START OF DATABASE CONTAINERS

  mariadb-schedule:
    image: mariadb
    restart: always
    ports:
      - 3310:3306
    environment:
      MARIADB_ROOT_PASSWORD: abc123
    volumes:
      - schedule_data:/var/lib/mysql/

  mongodb-artist:
    image: mongo
    restart: always
    ports:
      - 3307:27017
    volumes:
      - artist_data:/data/db

  mysql-food:
    image: mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - food_data:/var/lib/mysql

  mariadb-stage:
    image: mariadb
    restart: always
    ports:
      - 3309:3306
    environment:
      MARIADB_ROOT_PASSWORD: abc123
    volumes:
      - stage_data:/var/lib/mysql

  # START OF SERVICE CONTAINERS

  schedule-service:
    depends_on:
      - mariadb-schedule
    image: willemdebie/schedule-service
    ports:
      - 8081:8081
    links:
      - artist-service
      - food-service
      - stage-service
    environment:
      ARTIST_SERVICE_BASEURL: artist-service:8082
      FOOD_SERVICE_BASEURL: food-service:8083
      STAGE_SERVICE_BASEURL: stage-service:8084
      MARIADB_DB_USERNAME: root
      MARIADB_DB_PASSWORD: abc123
      MARIADB_DB_HOST: mariadb-schedule
      MARIADB_DB_PORT: 3306

  artist-service:
    depends_on:
      - mongodb-artist
    image: willemdebie/artist-service
    ports:
      - 8082:8082
    environment:
      MONGODB_HOST: mongodb-artist
      MONGODB_PORT: 3307

  food-service:
    depends_on:
      - mysql-food
    image: willemdebie/food-service
    ports:
      - 8083:8083
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-food
      MYSQL_DB_PORT: 3308

  stage-service:
    depends_on:
      - mariadb-stage
    image: willemdebie/stage-service
    ports:
      - 8084:8084
    environment:
      MARIADB_DB_USERNAME: root
      MARIADB_DB_PASSWORD: abc123
      MARIADB_DB_HOST: mariadb-stage
      MARIADB_DB_PORT: 3309

  # START OF API GATEWAY

  # api-gateway:
  #   depends_on:
  #     - schedule-service
  #     - artist-service
  #     - food-service
  #     - stage-service
  #   image: willemdebie/api-gateway
  #   ports:
  #     - 8080:8080
  #   environment:
  #     SCHEDULE_SERVICE_BASEURL: schedule-service:8081
  #     ARTIST_SERVICE_BASEURL: artist-service:8082
  #     FOOD_SERVICE_BASEURL: food-service:8083
  #     STAGE_SERVICE_BASEURL: stage-service:8084

  # START OF DATA VOLUMES

volumes:
  schedule_data:
  artist_data:
  food_data:
  stage_data:
