server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 661879216618-0gl8krhgkntc04h7m8qfvnp3k16datne.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: schedule-service
          uri: http://${SCHEDULE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/schedule
          filters:
            - SetPath=/api/schedule

        - id: schedule-service-all
          uri: http://${SCHEDULE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/schedules
            - Method=GET
          filters:
            - SetPath=/api/schedule/all

        - id: schedule-service-delete
          uri: http://${SCHEDULE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/schedule/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/schedule/{id}

        - id: artist-service
          uri: http://${ARTIST_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/artist
          filters:
            - SetPath=/api/artist

        - id: artist-service-all
          uri: http://${ARTIST_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/artists
            - Method=GET
          filters:
            - SetPath=/api/artist/all

        - id: artist-service-delete
          uri: http://${ARTIST_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/artist/{skuCode}
            - Method=DELETE
          filters:
            - SetPath=/api/artist/{skuCode}

        - id: foodItem-service
          uri: http://${FOOD_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/fooditem
          filters:
            - SetPath=/api/fooditem

        - id: foodTruck-service
          uri: http://${FOOD_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/foodtruck
          filters:
            - SetPath=/api/foodtruck

        - id: foodItem-service-all
          uri: http://${FOOD_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/fooditems
            - Method=GET
          filters:
            - SetPath=/api/fooditem/all

        - id: foodTruck-service-all
          uri: http://${FOOD_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/foodtrucks
            - Method=GET
          filters:
            - SetPath=/api/foodtruck/all

        - id: foodItem-service-delete
          uri: http://${FOOD_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/fooditem/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/fooditem/{id}

        - id: foodItem-service-delete
          uri: http://${FOOD_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/foodtruck/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/foodtruck/{id}

        - id: stage-service
          uri: http://${STAGE_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/stages
          filters:
            - SetPath=/api/stage

        - id: stage-service-all
          uri: http://${STAGE_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/stages
            - Method=GET
          filters:
            - SetPath=/api/stage/all

        - id: stage-service-delete
          uri: http://${STAGE_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/stage/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/stage/{id}