name: Build and deliver stage service

on: push

jobs:
  stage-service:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver stage service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt
      
      - name: Build, test and package project
        working-directory: ./stage-service
        run: mvn package -B

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/stage-service:latest ./stage-service

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/stage-service:latest
